# Generated by Django 5.2.6 on 2025-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('dress', 'dress'), ('cosmetics', 'cosmetics'), ('grocery', 'grocery'), ('shoes', 'shoes')], default=None, max_length=100),
        ),
    ]
