# Generated by Django 5.2.6 on 2025-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('dress', 'dress'), ('cosmetics', 'cosmetics'), ('grocery', 'grocery'), ('shoes', 'shoes'), ('watches', 'watches')], default=None, max_length=100),
        ),
    ]
