# Generated by Django 5.2.6 on 2025-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default='UnKnown', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=42),
        ),
    ]
