# Generated by Django 5.2.6 on 2025-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_seller_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
